"""
Empty script.mako for Alembic to generate migration files.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37a70c0b9f2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('instructors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_instructors_user_id', 'instructors', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notif_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_students_code', 'students', ['student_code'], unique=True)
    op.create_index('idx_students_user_id', 'students', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('activity_logs',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_student_id', 'activity_logs', ['student_id'], unique=False)
    op.create_table('courses',
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_instructor', 'courses', ['instructor_id'], unique=False)
    op.create_index('idx_courses_status', 'courses', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignments_course_id', 'assignments', ['course_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    op.create_index('idx_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_index('idx_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('idx_enrollments_student_id', 'enrollments', ['student_id'], unique=False)
    op.create_table('lessons',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lessons_course_id', 'lessons', ['course_id'], unique=False)
    op.create_index('idx_lessons_course_order', 'lessons', ['course_id', 'order_number'], unique=False)
    op.create_table('projects',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_course_id', 'projects', ['course_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quizzes_course_id', 'quizzes', ['course_id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('submission_url', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assignment_id', name='uq_asub_student_assignment')
    )
    op.create_index('idx_asub_status', 'assignment_submissions', ['status'], unique=False)
    op.create_index('idx_asub_student_id', 'assignment_submissions', ['student_id'], unique=False)
    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_attendance_student_lesson')
    )
    op.create_index('idx_attendance_lesson_id', 'attendance', ['lesson_id'], unique=False)
    op.create_index('idx_attendance_status', 'attendance', ['status'], unique=False)
    op.create_index('idx_attendance_student_id', 'attendance', ['student_id'], unique=False)
    op.create_table('instructor_notes',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_enrollment_id', 'instructor_notes', ['enrollment_id'], unique=False)
    op.create_table('predictions',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.String(length=50), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_calculated_at', 'predictions', ['calculated_at'], unique=False)
    op.create_index('idx_pred_classification', 'predictions', ['classification'], unique=False)
    op.create_index('idx_pred_enrollment_id', 'predictions', ['enrollment_id'], unique=False)
    op.create_index('idx_pred_enrollment_type', 'predictions', ['enrollment_id', 'score_type'], unique=False)
    op.create_table('project_submissions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('submission_url', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'project_id', name='uq_psub_student_project')
    )
    op.create_index('idx_psub_student_id', 'project_submissions', ['student_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_attempts_student_id', 'quiz_attempts', ['student_id'], unique=False)
    op.create_index('idx_quiz_attempts_student_quiz', 'quiz_attempts', ['student_id', 'quiz_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_enrollment_id', 'recommendations', ['enrollment_id'], unique=False)
    op.create_index('idx_rec_status', 'recommendations', ['status'], unique=False)
    op.create_table('video_progress',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('watched_percentage', sa.Float(), nullable=False),
    sa.Column('watch_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('last_position_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_video_progress_student_lesson')
    )
    op.create_index('idx_video_progress_student_id', 'video_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_progress_student_id', table_name='video_progress')
    op.drop_table('video_progress')
    op.drop_index('idx_rec_status', table_name='recommendations')
    op.drop_index('idx_rec_enrollment_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_quiz_attempts_student_quiz', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_student_id', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('idx_psub_student_id', table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index('idx_pred_enrollment_type', table_name='predictions')
    op.drop_index('idx_pred_enrollment_id', table_name='predictions')
    op.drop_index('idx_pred_classification', table_name='predictions')
    op.drop_index('idx_pred_calculated_at', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_notes_enrollment_id', table_name='instructor_notes')
    op.drop_table('instructor_notes')
    op.drop_index('idx_attendance_student_id', table_name='attendance')
    op.drop_index('idx_attendance_status', table_name='attendance')
    op.drop_index('idx_attendance_lesson_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('idx_asub_student_id', table_name='assignment_submissions')
    op.drop_index('idx_asub_status', table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index('idx_quizzes_course_id', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('idx_projects_course_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_lessons_course_order', table_name='lessons')
    op.drop_index('idx_lessons_course_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('idx_enrollments_student_id', table_name='enrollments')
    op.drop_index('idx_enrollments_status', table_name='enrollments')
    op.drop_index('idx_enrollments_course_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('idx_assignments_course_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('idx_courses_status', table_name='courses')
    op.drop_index('idx_courses_instructor', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_activity_student_id', table_name='activity_logs')
    op.drop_index('idx_activity_created_at', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_table('user_roles')
    op.drop_index('idx_students_user_id', table_name='students')
    op.drop_index('idx_students_code', table_name='students')
    op.drop_table('students')
    op.drop_table('role_permissions')
    op.drop_index('idx_notif_user_read', table_name='notifications')
    op.drop_index('idx_notif_user_id', table_name='notifications')
    op.drop_index('idx_notif_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_instructors_user_id', table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
