import React, { useEffect, useState } from 'react';
import { Award, Clock3, ShieldCheck } from 'lucide-react';
import { Card } from './UI';
import {
  flushCertificateAuditOutbox,
  getCertificateActivity,
  type CertificateActivitySummary,
  type CertificateProgramType,
} from '../../frontend/src/services/certificateAudit';

interface CertificateActivityCardProps {
  studentId?: string;
  programType: CertificateProgramType;
  refreshSignal: number;
}

const formatIssuedAt = (value: string | null) => {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  }).format(date);
};

export const CertificateActivityCard: React.FC<CertificateActivityCardProps> = ({
  studentId,
  programType,
  refreshSignal,
}) => {
  const [activity, setActivity] = useState<CertificateActivitySummary | null>(null);
  const [isLoading, setIsLoading] = useState(Boolean(studentId));

  useEffect(() => {
    if (!studentId) {
      setActivity(null);
      setIsLoading(false);
      return;
    }

    let active = true;
    const loadActivity = async () => {
      setIsLoading(true);
      try {
        await flushCertificateAuditOutbox();
        const nextActivity = await getCertificateActivity(studentId, programType);
        if (active) setActivity(nextActivity);
      } catch (error) {
        console.warn('Certificate activity could not be loaded.', error);
        if (active) setActivity(null);
      } finally {
        if (active) setIsLoading(false);
      }
    };

    const retryWhenOnline = () => { void loadActivity(); };
    void loadActivity();
    window.addEventListener('online', retryWhenOnline);
    return () => {
      active = false;
      window.removeEventListener('online', retryWhenOnline);
    };
  }, [studentId, programType, refreshSignal]);

  const issued = activity?.issued ?? false;
  const recordsLabel = `${activity?.total_issuance_records ?? 0} issuance ${(activity?.total_issuance_records ?? 0) === 1 ? 'record' : 'records'}`;

  return (
    <Card style={{ marginTop: '1.5rem', border: '1px solid var(--border-color)' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.9rem' }}>
        <div style={{
          width: 40,
          height: 40,
          display: 'grid',
          placeItems: 'center',
          borderRadius: '0.65rem',
          background: issued ? 'rgba(16, 185, 129, 0.12)' : 'rgba(148, 163, 184, 0.12)',
          color: issued ? '#10B981' : 'var(--text-muted)',
          flexShrink: 0,
        }}>
          {issued ? <Award size={20} aria-hidden="true" /> : <ShieldCheck size={20} aria-hidden="true" />}
        </div>
        <div style={{ minWidth: 0, flex: 1 }}>
          <p style={{ margin: 0, fontSize: '0.72rem', fontWeight: 700, letterSpacing: '0.08em', color: 'var(--text-muted)' }}>
            OFFICIAL RECORD
          </p>
          <h3 style={{ margin: '0.25rem 0 0', fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-main)' }}>
            Certificate Activity
          </h3>
        </div>
      </div>

      <div style={{
        marginTop: '1rem',
        padding: '1rem',
        borderRadius: '0.65rem',
        border: `1px solid ${issued ? 'rgba(16, 185, 129, 0.28)' : 'var(--border-color)'}`,
        background: issued ? 'rgba(16, 185, 129, 0.045)' : 'var(--bg-surface)',
      }}>
        {isLoading ? (
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.875rem' }}>Loading certificate activity…</p>
        ) : issued ? (
          <div style={{ display: 'grid', gap: '0.55rem' }}>
            <p style={{ margin: 0, fontWeight: 700, color: '#10B981' }}>Certificate issued</p>
            <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.875rem' }}>
              Last issued: <strong style={{ color: 'var(--text-main)' }}>{formatIssuedAt(activity?.last_issued_at ?? null)}</strong>
            </p>
            <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.875rem' }}>
              Generated by: <strong style={{ color: 'var(--text-main)' }}>{activity?.last_issued_by_name || 'Platform Administrator'}</strong>
            </p>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--text-muted)', fontSize: '0.8rem', paddingTop: '0.25rem' }}>
              <Clock3 size={14} aria-hidden="true" />
              <span>{recordsLabel}</span>
            </div>
          </div>
        ) : (
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.875rem', lineHeight: 1.55 }}>
            No certificate has been issued for this student yet. Each future certificate download will be recorded here.
          </p>
        )}
      </div>
    </Card>
  );
};
